# Move base node parameters. For full documentation of the parameters in this file, please see
#
# http://wiki.ros.org/costmap_2d
# http://wiki.ros.org/navigation/Tutorials/RobotSetup
#
acc_lim : 2.5
max_vel : 0.55
min_vel : -0.1

yaw_goal_tolerance : 0.05
xy_goal_tolerance : 0.10
latch_xy_goal_tolerance : false

sim_time : 1.7
sim_granularity : 0.025
vx_samples : 3
vy_samples : 10
vth_samples : 20
controller_frequency : 20.0

path_distance_bias  : 32.0
goal_distance_bias  : 24.0
occdist_scale : 0.01
forward_point_distance  : 0.325
stop_time_buffer : 0.2
scaling_speed  : 0.25
max_scaling_factor  : 0.2
publish_cost_grid  : false

oscillation_reset_dist : 0.05
prune_plan : true
