# Move base node parameters. For full documentation of the parameters in this file, please see
#
# http://www.ros.org/wiki/move_base
# http://wiki.ros.org/navigation/Tutorials/RobotSetup
#
shutdown_costmaps: false # example parameter

controller_frequency: 5.0 # example parameter
controller_patience: 3.0 # example parameter

planner_frequency: 1.0 # example parameter
planner_patience: 5.0 # example parameter

oscillation_timeout: 10.0 # example parameter
oscillation_distance: 0.2 # example parameter

# local planner - default is trajectory rollout
base_local_planner: "base_local_planner/TrajectoryPlannerROS" #parameters for local planners-"teb_local_planner/TebLocalPlannerROS", "dwa_local_planner/DWAPlannerROS", "base_local_planner/TrajectoryPlannerROS"
